"""Tests for output formatting."""

from __future__ import annotations

import json
from pathlib import Path

from sounddifff.report import render_json, render_terminal
from sounddifff.types import (
    AudioMetadata,
    ClipEvent,
    DetectionResult,
    DiffResult,
    LoudnessComparison,
    LoudnessResult,
    MetadataComparison,
    Segment,
    SegmentKind,
    SpectralBand,
    SpectralComparison,
    TemporalComparison,
)


def _make_result() -> DiffResult:
    """Create a sample DiffResult for testing."""
    return DiffResult(
        metadata=MetadataComparison(
            file_a=AudioMetadata(
                path="/tmp/a.wav",
                duration=10.0,
                sample_rate=48000,
                channels=2,
                bit_depth=16,
                format_name="WAV",
                frames=480000,
            ),
            file_b=AudioMetadata(
                path="/tmp/b.wav",
                duration=10.0,
                sample_rate=48000,
                channels=2,
                bit_depth=16,
                format_name="WAV",
                frames=480000,
            ),
        ),
        loudness=LoudnessComparison(
            file_a=LoudnessResult(lufs=-14.2, true_peak_dbtp=-1.1, loudness_range=8.2),
            file_b=LoudnessResult(lufs=-12.8, true_peak_dbtp=-0.3, loudness_range=6.4),
        ),
        spectral=SpectralComparison(
            bands=[
                SpectralBand("Low", 20, 250, -30.0, -29.2),
                SpectralBand("Mid", 250, 4000, -25.0, -24.7),
                SpectralBand("High", 4000, 20000, -35.0, -33.1),
            ]
        ),
        temporal=TemporalComparison(
            segments=[
                Segment(SegmentKind.SIMILAR, 0.0, 10.0, correlation=0.98),
            ],
            overall_correlation=0.98,
        ),
        detection=DetectionResult(
            clips=[ClipEvent("b.wav", 5.123, 0, 3)],
            silence_regions_a=[],
            silence_regions_b=[],
        ),
    )


class TestRenderTerminal:
    def test_contains_file_names(self) -> None:
        output = render_terminal(_make_result())
        assert "a.wav" in output
        assert "b.wav" in output

    def test_contains_lufs(self) -> None:
        output = render_terminal(_make_result())
        assert "LUFS" in output

    def test_contains_clipping_warning(self) -> None:
        output = render_terminal(_make_result())
        assert "Clipping" in output


class TestRenderJSON:
    def test_is_valid_json(self) -> None:
        output = render_json(_make_result())
        data = json.loads(output)
        assert "metadata" in data
        assert "loudness" in data
        assert "spectral" in data

    def test_contains_lufs_values(self) -> None:
        output = render_json(_make_result())
        data = json.loads(output)
        assert data["loudness"]["file_a"]["lufs"] == -14.2

    def test_segments_have_kind(self) -> None:
        output = render_json(_make_result())
        data = json.loads(output)
        assert data["temporal"]["segments"][0]["kind"] == "similar"


class TestHtmlReportFixes:
    """Fixes added by jaimefgdev, October 2026."""

    def _html(self, a: str, b: str) -> str:
        from sounddifff.core import diff
        from sounddifff.report import render_html

        fixtures = Path(__file__).parent / "fixtures"
        return render_html(diff(fixtures / a, fixtures / b))

    def test_template_ships_inside_the_package(self) -> None:
        import sounddifff

        assert (Path(sounddifff.__file__).parent / "templates" / "report.html.j2").is_file()
        assert "<h2>Spectral</h2>" in self._html("sine_a.wav", "sine_b.wav")

    def test_footer_shows_version_and_names_have_no_folders(self) -> None:
        from sounddifff import __version__

        html = self._html("sine_a.wav", "sine_b.wav")
        assert f"Generated by sounddifff {__version__}" in html
        assert "fixtures" not in html

    def test_long_issue_lists_are_capped(self) -> None:
        from sounddifff.report import MAX_LISTED_ISSUES

        html = self._html("clean.wav", "clipped.wav")
        assert html.count('class="issue"') == MAX_LISTED_ISSUES + 1
        assert "more clipping events" in html
